services:
  bot:
    image: ghcr.io/downloadablefox/twotto:main
    container_name: zwerl-twotto
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      DEBUG: ${DEBUG}
      TOKEN: ${TOKEN}
    depends_on:
      - db
  db:
    image: postgres:12
    container_name: zwerl-twotto-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: